# Generated by Django 6.0.3 on 2026-03-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='internship_certificates/'),
        ),
        migrations.AddField(
            model_name='application',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
