# Generated by Django 6.0.3 on 2026-04-01 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_application_certificate_application_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='roll_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
