# Generated by Django 6.0.3 on 2026-05-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_internship_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
