# Generated by Django 6.0.3 on 2026-04-01 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('internships', '0003_application_joined_date_application_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internships.internship'),
        ),
    ]
