# Generated by Django 6.0.3 on 2026-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
