# Generated by Django 6.0.3 on 2026-03-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_enrollment_unique_together_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
