# Generated by Django 6.0.3 on 2026-03-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_company_material_class_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='trainer_resumes/'),
        ),
    ]
