# Generated by Django 6.0.3 on 2026-03-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizbatch',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
